# Generated by Django 6.0.7 on 2026-07-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('spercial_status', 'Can read books')]},
        ),
    ]
